version: '3.8'

services:
  students:
    image: students
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    restart: on-failure
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      # PG_HOST: ${PG_HOST}
      # PG_PORT: ${PG_PORT}
      # PG_USER: ${PG_USER}
      # PG_PASSWORD: ${PG_PASSWORD}
      # PG_DATABASE: ${PG_DATABASE}
    ports:
      - "8080:8080"